name: delivery
env:
  DH_REPO_NAME       : "ttre16/${{ github.event.client_payload.repo_name }}"
  SERVICE_NAME       : "briana_stack_${{ github.event.client_payload.service_name }}"
  IMAGE_TAG          : "${{ github.event.client_payload.commit_hash }}"
  IMAGE_NAME         : "$DH_REPO_NAME:$IMAGE_TAG"
  DISPATCH_REPO      : "briana-crm/briana-deploy"
  UPDATE_EVENT_TYPE  : "rolling_update"
  DISPATCH_PAYLOAD   : '{"service_name": "$SERVICE_NAME", "image_name": "$IMAGE_NAME" }'

on:
  push:
    branches: [main]

jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: '12'

      - name: Install dependencies and build project
        run: |
          npm install
          npm run build

      - name: Build image and push it to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.DH_REPO_NAME }}
          tags: ${{ env.IMAGE_TAG }},latest

      - name: Dispatch rolling update action
        uses: peter-evans/repository-dispatch@v1.1.3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ env.DISPATCH_REPO }}
          event-type: ${{ env.UPDATE_EVENT_TYPE }}
          client-payload: ${{ env.DISPATCH_PAYLOAD }}
