name: test

on:
  pull_request:
    branches: [development]

jobs:
  test:
    name: Continuous integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: '12'

      - name: Install dependencies and run tests
        run: |
          npm install
          npm run test
